"""Seed reviews for ReplyRush. Pre-tagged with themes + flags (no AI on Connect).
Designed so the Issue Radar lights up right after the first Connect:
'Delivery/Wait time' and 'Staff/Service' complaints spread across platforms.
"""

# themes must come from this canonical set:
# Product quality, Delivery/Wait time, Staff/Service, Pricing/Value,
# Cleanliness/Environment, Order accuracy, Refund/Billing, Other

SEED_REVIEWS = {
    "google": [
        {
            "reviewer_name": "Marcus Bennett",
            "rating": 1,
            "text": "Waited over 50 minutes just to be seated even with a reservation, and the host was dismissive when I complained. If I don't hear back I'm reporting this to corporate and leaving reviews everywhere.",
            "days_ago": 2,
            "flag": "red",
            "sentiment": "negative",
            "themes": ["Staff/Service", "Delivery/Wait time"],
            "language": "en",
        },
        {
            "reviewer_name": "Aisha Rahman",
            "rating": 5,
            "text": "Absolutely lovely spot! The staff remembered my name from last time and the flat white was perfect. Cosy atmosphere too.",
            "days_ago": 5,
            "flag": "green",
            "sentiment": "positive",
            "themes": ["Staff/Service"],
            "language": "en",
        },
        {
            "reviewer_name": "Tomasz Kowalski",
            "rating": 3,
            "text": "Food was decent but we waited nearly 40 minutes for a simple table on a quiet Tuesday. Could be better organised.",
            "days_ago": 8,
            "flag": "yellow",
            "sentiment": "negative",
            "themes": ["Delivery/Wait time"],
            "language": "en",
        },
        {
            "reviewer_name": "Grace Miller",
            "rating": 5,
            "text": "Spotlessly clean, plants everywhere, and the restrooms were immaculate. A really pleasant environment to work from for a couple of hours.",
            "days_ago": 12,
            "flag": "green",
            "sentiment": "positive",
            "themes": ["Cleanliness/Environment"],
            "language": "en",
        },
        {
            "reviewer_name": "David Osei",
            "rating": 2,
            "text": "The coffee is good but £6.50 for a small latte is steep, and they now charge extra for oat milk. Feels overpriced for the area.",
            "days_ago": 15,
            "flag": "yellow",
            "sentiment": "negative",
            "themes": ["Pricing/Value"],
            "language": "en",
        },
    ],
    "zomato": [
        {
            "reviewer_name": "Rohan Malhotra",
            "rating": 1,
            "text": "Order arrived almost 2 hours late and completely cold. The biryani was inedible. Nobody answered the support line. I want a full refund or I'm reporting this restaurant to Zomato.",
            "days_ago": 1,
            "flag": "red",
            "sentiment": "negative",
            "themes": ["Delivery/Wait time", "Product quality"],
            "language": "en",
        },
        {
            "reviewer_name": "Nadia Haddad",
            "rating": 3,
            "text": "Food tasted fine but delivery was 45 minutes past the promised time and arrived lukewarm. Please tighten up the timings.",
            "days_ago": 4,
            "flag": "yellow",
            "sentiment": "negative",
            "themes": ["Delivery/Wait time"],
            "language": "en",
        },
        {
            "reviewer_name": "Kenji Watanabe",
            "rating": 5,
            "text": "The paneer tikka and garlic naan were outstanding, packed hot and fresh. Easily the best delivery I've had this month.",
            "days_ago": 7,
            "flag": "green",
            "sentiment": "positive",
            "themes": ["Product quality"],
            "language": "en",
        },
        {
            "reviewer_name": "Priya Nair",
            "rating": 2,
            "text": "I ordered two veg thalis and received one chicken meal and one wrong curry. The order was completely mixed up.",
            "days_ago": 10,
            "flag": "yellow",
            "sentiment": "negative",
            "themes": ["Order accuracy"],
            "language": "en",
        },
        {
            "reviewer_name": "Lucía Fernández",
            "rating": 5,
            "text": "¡La comida estaba deliciosa y llegó calientita! Los tacos al pastor son increíbles y el repartidor fue muy amable. Volveré a pedir sin duda.",
            "days_ago": 13,
            "flag": "green",
            "sentiment": "positive",
            "themes": ["Product quality"],
            "language": "es",
        },
    ],
    "amazon": [
        {
            "reviewer_name": "Brandon Cole",
            "rating": 1,
            "text": "The blender arrived with a cracked jug and the motor died on day two. I've requested a refund twice with no response. If this isn't resolved I'm filing a chargeback and reporting the seller.",
            "days_ago": 2,
            "flag": "red",
            "sentiment": "negative",
            "themes": ["Product quality", "Refund/Billing"],
            "language": "en",
        },
        {
            "reviewer_name": "Elena Popescu",
            "rating": 3,
            "text": "The product itself works but the box was crushed and the outer packaging was torn when it arrived. Lucky it wasn't damaged inside.",
            "days_ago": 6,
            "flag": "yellow",
            "sentiment": "negative",
            "themes": ["Product quality"],
            "language": "en",
        },
        {
            "reviewer_name": "Samuel Adeyemi",
            "rating": 5,
            "text": "Fantastic little coffee grinder. Consistent grind, quiet motor, and it looks great on the counter. Exactly as described.",
            "days_ago": 9,
            "flag": "green",
            "sentiment": "positive",
            "themes": ["Product quality"],
            "language": "en",
        },
        {
            "reviewer_name": "Hannah Schmidt",
            "rating": 2,
            "text": "I was charged twice for a single order and my statement shows two separate transactions. Still waiting for the duplicate charge to be reversed.",
            "days_ago": 11,
            "flag": "yellow",
            "sentiment": "negative",
            "themes": ["Refund/Billing"],
            "language": "en",
        },
        {
            "reviewer_name": "Oliver Grant",
            "rating": 5,
            "text": "Shipped a day early and arrived perfectly packaged. Setup took two minutes. Really happy with this purchase.",
            "days_ago": 16,
            "flag": "green",
            "sentiment": "positive",
            "themes": ["Delivery/Wait time"],
            "language": "en",
        },
    ],
    "yelp": [
        {
            "reviewer_name": "Chloe Robinson",
            "rating": 2,
            "text": "The stylist barely spoke to me and seemed annoyed I asked to adjust the length. The cut was fine but the attitude at the front desk left a bad taste.",
            "days_ago": 3,
            "flag": "yellow",
            "sentiment": "negative",
            "themes": ["Staff/Service"],
            "language": "en",
        },
        {
            "reviewer_name": "Isabella Costa",
            "rating": 5,
            "text": "Best haircut I've had in years! Mia listened to exactly what I wanted and the head massage during the wash was heavenly. Booking again.",
            "days_ago": 6,
            "flag": "green",
            "sentiment": "positive",
            "themes": ["Staff/Service"],
            "language": "en",
        },
        {
            "reviewer_name": "Camille Laurent",
            "rating": 2,
            "text": "Le service était vraiment lent, j'ai attendu 30 minutes après l'heure de mon rendez-vous et personne ne s'est excusé. Dommage car la coupe était correcte.",
            "days_ago": 9,
            "flag": "yellow",
            "sentiment": "negative",
            "themes": ["Delivery/Wait time", "Staff/Service"],
            "language": "fr",
        },
        {
            "reviewer_name": "Nathan Wright",
            "rating": 5,
            "text": "Immaculate salon, calming music, and they offered me tea while I waited. Such a relaxing, clean environment.",
            "days_ago": 14,
            "flag": "green",
            "sentiment": "positive",
            "themes": ["Cleanliness/Environment"],
            "language": "en",
        },
        {
            "reviewer_name": "Sofia Greco",
            "rating": 2,
            "text": "$85 for a basic trim and blow-dry feels excessive, especially with the extra charges added at checkout that weren't mentioned upfront.",
            "days_ago": 18,
            "flag": "yellow",
            "sentiment": "negative",
            "themes": ["Pricing/Value"],
            "language": "en",
        },
    ],
    "instagram": [
        {
            "reviewer_name": "@jenna.travels",
            "rating": 2,
            "text": "I've DM'd you three times about my missing item and got no reply 😒 kind of disappointing for a brand this size.",
            "days_ago": 2,
            "flag": "yellow",
            "sentiment": "negative",
            "themes": ["Staff/Service"],
            "language": "en",
        },
        {
            "reviewer_name": "@marco_eats",
            "rating": 5,
            "text": "Obsessed with my order 😍 the packaging is gorgeous and everything tasted amazing. You've got a customer for life!",
            "days_ago": 4,
            "flag": "green",
            "sentiment": "positive",
            "themes": ["Product quality"],
            "language": "en",
        },
        {
            "reviewer_name": "@dan.k",
            "rating": 1,
            "text": "Still waiting on the order I placed LAST WEEK and no tracking, no updates. This is unacceptable. Sort it out or I'm reporting the page.",
            "days_ago": 1,
            "flag": "red",
            "sentiment": "negative",
            "themes": ["Delivery/Wait time"],
            "language": "en",
        },
        {
            "reviewer_name": "@lifewithlia",
            "rating": 5,
            "text": "Genuinely the best little cafe in town ❤️ the team is always so warm and welcoming. Sending everyone your way!",
            "days_ago": 8,
            "flag": "green",
            "sentiment": "positive",
            "themes": ["Staff/Service"],
            "language": "en",
        },
        {
            "reviewer_name": "@thrifty_sam",
            "rating": 3,
            "text": "love the products but the prices went up again 😕 getting a bit hard to justify as a regular.",
            "days_ago": 12,
            "flag": "yellow",
            "sentiment": "negative",
            "themes": ["Pricing/Value"],
            "language": "en",
        },
    ],
}

PLATFORMS = ["google", "zomato", "amazon", "yelp", "instagram"]
